### ISSUE TITLE
Score hidden behind buttons

### ISSUE THREAD

**Issue by jespertheend** [yuhuili/TouchBarDino#2]
How did you manage to get rid of the buttons on the right side of the touch bar?
I removed them all in settings but I still have the tiny arrow button.

**Comment by yuhuili** [comment]
If you go to System Preferences->Keyboard, you can choose what Touch Bar shows. App Control option would hide those system icons and the arrow.
<img width="780" alt="screen shot 2017-06-25 at 12 00 07 pm" src="https://user-images.githubusercontent.com/8474807/27517680-26490546-599e-11e7-9bce-cc690f147b65.png">

**Comment by jespertheend** [comment]
Ah thanks! I wonder if there's an easy way for applications to temporarily change this setting.
